development:
  adapter: postgresql
  encoding: unicode
  database: melle_development
  host: localhost
  pool: 20
  #username: sharefi
  #password: 

test:
  adapter: postgresql
  encoding: unicode
  database: melle_test
  host: localhost
  pool: 20
  #username: sharefi
  #password:

production:
  adapter: postgresql
  encoding: unicode
  database: melle_production
  host: localhost
  pool: 20
  username: melle
  password:
