# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 010796af9f90ea0fa918c779869190ae1085b28f409c88d2a9ca73d1e414598ae8ebd2c0fa9e96bcf9c95d2265e39d0725d0b3fffc6feaef4441c966eeaffa29

test:
  secret_key_base: 420e8576d2412d339147a9db5c3a561f8082764d4e9453905e8bcb4c18f0517a6bb264e55f27a4c9496d82623bbabc2e7ad340141f7f8d9f15a24283cc3c4c54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
